import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const read=n=>readFileSync(`reference/${n}.md`,'utf8').replace(/\r/g,'');
const esc=t=>t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const inline=t=>esc(t.replace(/\\&/g,'&').replace(/\*+/g,'')).replace(/https:\/\/[^\s<]+/g,u=>`<a href="${u}" target="_blank" rel="noopener noreferrer">${u.includes('roblox.com/catalog')?'View on Roblox ↗':u}</a>`);
function document(n){return read(n).trim().split(/\n\s*\n/).slice(1).map(b=>{const tag=/^Rule \d+ \||^\*\*\*|^(Restricted Vehicles|Restricted Weapons):/.test(b)?'h2':'p';return `<${tag}>${inline(b).replace(/\n/g,'<br>')}</${tag}>`}).join('\n')}
const names=['Florida Highway Patrol',"Hillsborough County Sheriff's Office",'Tampa Fire Department','Tampa Police Department','Department Hub','Special Response Team','Florida Department of Transportation','Florida Government'];
const abbr=['FHP','HCSO','TFD','TPD','HUB','SRT','FDOT','GOV'];
const source=read('Florida State Departments');
const departments=names.map((name,i)=>{const s=source.slice(source.indexOf(name)+name.length).trim();return {name,abbr:abbr[i],description:s.split('https:')[0].trim(),url:s.match(/https:\/\/discord\.gg\/\w+/)[0]}});
const cards=items=>items.map(d=>`<article class="card department"><span class="tag">${d.abbr}</span><h2>${esc(d.name)}</h2><p>${esc(d.description)}</p><a class="text-link" href="${d.url}" target="_blank" rel="noopener noreferrer">Visit department Discord ↗</a></article>`).join('');
const nav=[['','Overview','◈'],['sessions','Sessions','◷'],['departments','Departments','▦'],['rules','Regulations','≡'],['shop','Community shop','◇'],['about','About Florida','◎']];
const banner=n=>`<img class="banner" src="/public/brand/${n}.png" alt="Florida State Roleplay ${n}" width="3000" height="750">`;
const discord='<a class="button" href="https://discord.gg/fsrp" target="_blank" rel="noopener noreferrer">Join our Discord ↗</a>';
const heading=(t,d)=>`<div class="heading"><span class="eyebrow">FLORIDA STATE ROLEPLAY</span><h1>${t}</h1><p>${d}</p></div>`;
const pages={
'':{title:'Overview',body:`${heading('Welcome to Florida.','Your community. Your story. Everything you need in one place.')}${banner('dashboard')}<div class="banner-foot"><span>THE SUNSHINE STATE IS CALLING</span>${discord}</div><div class="facts"><div><small>THE EXPERIENCE</small><strong>Florida roleplay</strong></div><div><small>OUR DEPARTMENTS</small><strong>8 ways to belong</strong></div><div><small>SESSION SCHEDULE</small><strong>Daily · around 11:30 AM</strong></div></div><div class="home-grid"><section><div class="section-heading"><h2>Find your place</h2><a href="/departments/">All departments ↗</a></div><div class="grid">${cards(departments.slice(0,4))}</div></section><aside><section class="card"><span class="tag">NEXT SESSION</span><h2>The next story is yours.</h2><p>Sessions are hosted daily around 11:30 AM. Check Discord for session announcements and schedule changes.</p><a class="button secondary" href="/sessions/">Session information</a></section><section class="card accent"><span class="eyebrow">MAKE EVERY SCENE COUNT</span><h2>Good roleplay<br>starts with you.</h2><p>Get familiar with the regulations before heading onto the streets.</p><a class="button" href="/rules/">Read the regulations</a></section><section class="card"><h2>A community beyond the game.</h2><p>Meet other members, find department opportunities, and keep up with Florida.</p>${discord}</section></aside></div>`},
sessions:{title:'Sessions',body:`${heading('See you on the streets.','Everything you need for your next Florida session.')}${banner('sessions')}<section class="card feature"><span class="tag">DAILY SESSIONS</span><h2>Around 11:30 AM</h2><p>Sessions are hosted daily around 11:30 AM. Session updates and schedule changes are announced in our Discord.</p>${discord}<p>Check the latest announcement before joining.</p></section>`},
departments:{title:'Departments',body:`${heading('Serve your community.','Different uniforms. One community.')}${banner('departments')}<p class="intro">Explore each department and join its Discord for opportunities and information. For questions, open a General Support ticket in that department’s server.</p><div class="grid">${cards(departments)}</div>`},
rules:{title:'Regulations',body:`${heading('Keep every scene fair.','The community handbook for Florida State Roleplay.')}${banner('rules')}<nav class="tabs" aria-label="Regulation categories"><a href="#game">Game regulations</a><a href="#unwhitelisted">Unwhitelisted regulations</a><a href="#restricted">Restricted items</a></nav><article class="card prose" id="game"><span class="tag">COMMUNITY HANDBOOK</span><h2>Game regulations</h2>${document('Game Regulations')}</article><article class="card prose" id="unwhitelisted"><h2>Unwhitelisted regulations</h2>${document('Unwhitelisted Regulations')}</article><article class="card prose" id="restricted"><h2>Restricted items</h2>${document('Restricted Items')}</article>`},
shop:{title:'Community shop',body:`${heading('Support your community.','Memberships, apparel, and more from Florida State Roleplay.')}${banner('shop')}<div class="notice">Purchases take place on Roblox. After purchasing, open a Discord support ticket to redeem your item. Membership descriptions differ in a few places; confirm current perks with support before buying.</div><article class="card prose shop-content">${readFileSync('reference/shop-content.html','utf8')}</article>`},
about:{title:'About Florida',body:`${heading('One community. Countless stories.','Roleplay like no other.')}${banner('dashboard')}<section class="card prose"><h2>Welcome to Florida State Roleplay.</h2><p>A Florida-inspired community in Emergency Response: Liberty County. Patrol the highways, answer the call, or build your own civilian story.</p><p>This is your information hub for departments, sessions, regulations, and the community shop. Join Discord for announcements, support, and department opportunities.</p><div class="actions">${discord}<a class="button secondary" href="https://www.roblox.com/communities/1082694446" target="_blank" rel="noopener noreferrer">Our Roblox group ↗</a></div></section>`}
};
function shell(key,p){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Florida State Roleplay server information, sessions, departments, regulations and community shop."><title>${p.title} | Florida State Roleplay</title><link rel="icon" href="/public/brand/logo.gif"><link rel="stylesheet" href="/site.css"><link rel="canonical" href="https://fsrp.xyz/${key?key+'/':''}">${key==='shop'?'<script src="/shop/shop.js" defer></script>':''}</head><body><a class="skip" href="#main">Skip to content</a><aside class="sidebar"><a class="brand" href="/"><img src="/public/brand/logo.gif" alt="" width="44" height="44"><span>FSRP<small>FLORIDA STATE ROLEPLAY</small></span></a><span class="nav-label">COMMUNITY</span><nav aria-label="Main navigation">${nav.map(([r,l,i])=>`<a href="/${r?r+'/':''}" ${r===key?'aria-current="page"':''}><span aria-hidden="true">${i}</span>${l}</a>`).join('')}</nav><div class="sidebar-bottom"><h3>A community beyond the game.</h3><p>Find your people in our Discord.</p><a href="https://discord.gg/fsrp" target="_blank" rel="noopener noreferrer">Join the community ↗</a><small>FSRP · Roleplay like no other.</small></div></aside><div class="main-shell"><header class="topbar"><span>Community hub <b>/ ${p.title}</b></span><a href="https://discord.gg/fsrp" target="_blank" rel="noopener noreferrer">Join Discord ↗</a></header><main id="main">${p.body}</main><footer><span>Florida State Roleplay</span><span>Independent community · Not affiliated with Roblox or PRC.</span></footer></div></body></html>`}
for(const [key,p] of Object.entries(pages)){if(key)mkdirSync(key,{recursive:true});writeFileSync(key?`${key}/index.html`:'index.html',shell(key,p))}
writeFileSync('404.html',shell('404',{title:'Page not found',body:`${heading('Let’s get you back to Florida.','This page is no longer here.')}<a class="button" href="/">Back to the community hub</a>`}));
writeFileSync('.nojekyll','');
console.log('Built six static pages and a 404 page. No runtime dependencies.');
